
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjaibparbbirqvjapfmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqYWlicGFyYmJpcnF2amFwZm1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNDYxNzgsImV4cCI6MjA1MzYyMjE3OH0.8VCrQDrOdsOdHUSKWx0s9yrZb59pYsJGf7Tu2u8t7DU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
